### ISSUE TITLE
Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token

### ISSUE THREAD

**Issue by johanmynhardt** [Afrozaar/wp-api-v2-client-java#11]
```
Wrapped by: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@4ae32ea0; line: 1, column: 327] (through reference chain: com.afrozaar.wordpress.wpapi.v2.model.User["capabilities"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: java.io.PushbackInputStream@4ae32ea0; line: 1, column: 327] (through reference chain: com.afrozaar.wordpress.wpapi.v2.model.User["capabilities"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:225) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:209) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:95) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:835) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:819) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:599) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:534) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange0(Client.java:734) ~[na:na]
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange0(Client.java:740) ~[na:na]
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange1(Client.java:753) ~[na:na]
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange1(Client.java:744) ~[na:na]
	at com.afrozaar.wordpress.wpapi.v2.Client.getUser(Client.java:625) ~[na:na]
```

**Comment by johanmynhardt** [comment]
Issue submitted at https://github.com/WP-API/WP-API/issues/2426 but in the meantime I discovered that Jackson has a flag that can be enabled for deserialization for occurrences of this:

```
DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_EMPTY_OBJECT
```

For now I will enable this flag until it is fixed in WP-API.
