### ISSUE TITLE
RestClientException when trying to create a post

### ISSUE THREAD

**Issue by aleyeeey** [Afrozaar/wp-api-v2-client-java#64]
Hey there,

I am getting a RestClientException:
`Exception in thread "main" org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class com.afrozaar.wordpress.wpapi.v2.model.Post] and content type [text/html;charset=UTF-8]`

Is this repository still supported with Wordpress 5.x?

**Comment by clintonbosch** [comment]
WordPress 5 does not have Rest API as part of core, so you would need to install the REST API plugin at the very least. If you have already done that then test the API with a curl call to https://your.website/wp-json/wp/v2/posts to see that you are getting the expected json response

**Comment by aleyeeey** [comment]
@clintonbosch I already tested it! It works with postman, I am also getting a response. And I looked up the content type in postman and it was json. So, what is happening here?

Strange thing: the curl call gives me indeed a text/html response...

> <head><title>Document Moved</title></head>
> <body><h1>Object Moved</h1>This document may be found <a HREF="https://your.website/wp-json/">here</a></body>

But I strangely have no problem in getting a response in Postman?

Edit: I got the curl call working, since this is a dev-site I have no ssl-cert so I make my curl call like this

`curl --user 'customuser:custompassword' --insecure https://your.website/wp-json/wp/v2/posts`

I looked something like this up in your repository and saw that I can handle this problem with `requestFactory`, so I've done that like this:

```java
public Wordpress createClient() throws NoSuchAlgorithmException, KeyStoreException, KeyManagementException {
        TrustStrategy acceptingTrustStrategy = (X509Certificate[] chain, String authType) -> true;

        SSLContext sslContext = org.apache.http.ssl.SSLContexts.custom()
                .loadTrustMaterial(null, acceptingTrustStrategy)
                .build();

        SSLConnectionSocketFactory csf = new SSLConnectionSocketFactory(sslContext);

        CloseableHttpClient httpClient = HttpClients.custom()
                .setSSLSocketFactory(csf)
                .build();

        HttpComponentsClientHttpRequestFactory requestFactory =
                new HttpComponentsClientHttpRequestFactory();

        requestFactory.setHttpClient(httpClient);

        final ClientFactory.Builder builder = ClientFactory.builder(ClientConfig.of(BASE_URL, USERNAME, PASSWORD, true, DEBUG)).withRequestFactory(requestFactory);
        return builder.build();
    }
```

But the problem is now, that I get this exception:
 `Exception in thread "main" org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://your.website?rest_route=/wp/v2/posts":Certificate for <your.website> doesn't match any of the subject alternative names: []; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for <your.website> doesn't match any of the subject alternative names: []
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:545)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:507)
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange0(Client.java:927)
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange0(Client.java:933)
	at com.afrozaar.wordpress.wpapi.v2.Client.doExchange1(Client.java:952)
	at com.afrozaar.wordpress.wpapi.v2.Client.createPost(Client.java:179)
	at com.afrozaar.wordpress.wpapi.v2.Client.createPost(Client.java:187)
	at CustomPostType.createTestPostWithMetaData(CustomPostType.java:44)
	at CustomPostType.main(CustomPostType.java:73)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <your.website> doesn't match any of the subject alternative names: []
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569)
	... 9 more`
